FROM node:22-alpine
WORKDIR /app
RUN apk add --no-cache libc6-compat openssl postgresql-client bash
COPY package.json package-lock.json* ./
RUN npm install
COPY . .
RUN npx prisma generate
EXPOSE 3000
CMD ["sh", "-c", "npx prisma migrate deploy && npx tsx prisma/seed.ts && npm run dev"]